config/routes.rb
Rails.application.routes.draw do
  
  namespace :main do
    get :index
    get :start
    get :status
  end

  root 'main#index'

end

app/models/stat.rb
class Stat < ActiveRecord::Base
	
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception



end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include ThreadsPad::Helper
  before_action :get_pad


  def start
  	@cancel = false
  	
  	if  !ThreadsPad::Pad.done?
            #cancel
  		ThreadsPad::Pad.terminate
  		@cancel = true
  	else	
	  	start_parsing params[:threads]  if params[:threads].present?
  	end
  end

  def get_pad
  	@pad = ThreadsPad::Pad.new session[:pad_id]	
  end
  
  def index
  	
  end

  def status
  

  end

private
  
  def start_parsing threads
     # find out amount of lines in first tab of csv file
      fn = File.join Rails.root, 'public', 'demo.csv'
      csv = Roo::Spreadsheet.open(fn)
      sheet = csv.sheet(0)
      #div total amount of lines on number of threads
      chunk_length = sheet.count / threads.count
      mod = sheet.count % threads.count
      
      threads.count.times do |index|  
        if index == 0
         @pad << CsvImportJob.new(fn, index + 1 , chunk_length + mod) 
        else
          @pad << CsvImportJob.new(fn, index * chunk_length + mod + 1, chunk_length) 
        end
      end
      
      Unit.delete_all
      @pad.destroy_old
      session[:started_at] = Time.now
      session[:threads_count] = threads.count

      #add events

      @pad.on :finish do |j|
        j.debug "Done at #{Time.now}"
        j.debug "Amount of units is #{Unit.count}"
        finish_date =  Time.now
        puts "started_at: #{session[:started_at]} #{session[:started_at].class.name}"
        delta = (finish_date - session[:started_at]).round(2)
        j.debug "Time delta #{delta} s" if session[:started_at].present? 
        Stat.create! percents: @pad.current, threads_count: session[:threads_count], start: session[:started_at], finish: finish_date, time_delta: delta
      end
      @pad.on(5) { |j| j.debug 'This is message is generated by event that is bind to 5% '}
      @pad.on(15) { |j| j.debug 'Events are easy to bind'}
      @pad.on(30) { |j| j.debug 'For example, this message is bind like: @pad.on(30) { |j| j.debug \'For example, this message is bind like: @pad.on(15) { |j| j.debug \'For example, this message is bind like: \'}\'}'}
      @pad.on(50) { |j| j.debug 'Make sure you do not relay on 100% as finish of work'}
      @pad.on(65) { |j| j.debug 'I\'d better use @pad.on(:finish) {...} it 100% garanteed that it\'s fired when all works are finished'}
      @pad.on(90..95) { |j| j.debug 'Ok. It\s about to finish'}
      @pad.on(98) { |j| j.debug 'ps: Check graphs on the right it. '}
      
      session[:pad_id] =  @pad.start
      
      @pad.log "Started at #{Time.now}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
	def format_log log
		"#{log[:msg]}\<br\>".html_safe
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thread Pad Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75333935-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/main/_graph.haml
%h2 Stats're based on successfully finished jobs
= column_chart Stat.where('percents >= 100').group(:threads_count).average(:time_delta),  xtitle: "Threads", ytitle: "Avg Delta, s"
%h2 Last 15 records
%table.table
	%thead
		%th Start
		%th Finish
		%th Delta, sec
		%th Percents
		%th Threads Count

	%tbody
		- Stat.last(15).each do |stat|
			%tr
				%td=stat.start
				%td=stat.finish
				%td=stat.time_delta
				%td=stat.percents
				%td=stat.threads_count

app/views/main/index.html.haml
%center
	%h1 CSV Parsing  Example
.col-md-offset-1.col-md-5.col-sm-offset-1.col-sm-5
	%p="Here is a #{link_to('csv file', root_url + 'demo.csv')}. It contains 10000 lines. With ThreadsPad gem we can split a parsing process into a few chunks and run them at same time.".html_safe

	

	
	=form_tag main_start_path, method: :get, remote: true do 
		
		%h2 Amount of parsing threads. 
		%ul.checkbox
			%li
				=label_tag do
					=check_box_tag 'threads[]', 1, true, id: 'threads_1'
					1 Parsing Job
			%li
				=label_tag do
					=check_box_tag 'threads[]', 2, false, id: 'threads_2'
					2 Parsing Job
			%li
				=label_tag do
					=check_box_tag 'threads[]', 3, false, id: 'threads_3'
					3 Parsing Job
			%li
				=label_tag do
					=check_box_tag 'threads[]', 4, false, id: 'threads_4'
					4 Parsnig Job
			%li
				=label_tag do
					=check_box_tag 'threads[]', 5, false, id: 'threads_5'
					5 Parsing Job
		The parsing job consist of following processes:
		%ul
			%li reading a csv file
			%li parsing a bunch of lines
			%li saving mined data into DB
		%h2 Let's try it
		=button_tag 'Start', class: 'btn btn-lg btn-default start'

		
	
	.row
	%center
	%h2
		%span#percents=@pad.current || 0
		='%'
	%br
	%h2 Logs
	You can refresh the page, but logs won't disappear
	#logs
		-@pad.logs.each do |l|
			=format_log l
.col-md-6.col-sm-6
	#graph=render partial: 'graph'
-if !@pad.done?	
	:javascript
		enable_buttons(false)
		start_import_timer()